version: '3'
services:
  api:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis
      - mongodb
  mongodb:
      image: mongo:latest
      restart: always
      ports:
        - 27017:27017
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379