version: '3'
services:
  api:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis
      - mongodb
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  # postgres:
  #   image: postgres:latest
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_DB=covid
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=12345678
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  neo4j:
    image: neo4j:latest
    restart: always
    ports:
      - 7474:7474
      - 7687:7687

  cassandra:
    image: cassandra:latest
    restart: always
    ports:
      - 7000:7000

volumes:
  postgres-data:
    driver: local