version: '3'
services:
  api:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis
      - neo4j
      - cassandra
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  neo4j:
    image: neo4j:latest
    restart: always
    volumes:
      - ./src/resources/:/var/lib/neo4j/import/
    ports:
      - 7474:7474
      - 7687:7687

  cassandra:
    image: cassandra:latest
    restart: always
    ports:
      - 9042:9042